apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: underwriting-agent
  namespace: underwriting-agent
  labels:
    app.kubernetes.io/name: underwriting-agent
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: underwriting-agent
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s
